### ISSUE TITLE
Download dei materiali non funzionante

### ISSUE THREAD

**Issue by mark99-19** [mpindaro/little-mermaid-downloader#1]
### Contesto:

- **OS utilizzato:** Ubuntu, Windows
- **versione di Python:** 3
- **requisiti installati:** sì
- **FFmpeg installato:** sì
- **descrizione del problema:** Dando il comando `python3 downloader.py <url ariel> <cookie>`, lo script restituisce il seguente output:

> Ho finito di scaricare slide e altri materiali.
> Finito!

Controllando la directory di dove viene eseguito lo script però, non vi è alcun materiale scaricato.
Preciso che
1. il cookie è "ariel-auth", generato e copiato al momento del login.
2. il sito utilizzato è del formato https://<nomesito>.ariel.ctu.unimi.it/<qualcosa>, con "qualcosa" uguale ad esempio a
`v5/frm3/ThreadList.aspx?name=contenuti`

**Comment by mpindaro** [comment]
Ciao, potresti mandarmi il link della pagina ariel?

**Comment by mark99-19** [comment]
Ciao! Questo è un esempio, penso dovresti riuscire ad averne l'accesso: https://gprossirwm.ariel.ctu.unimi.it/v5/home/Default.aspx

**Comment by mpindaro** [comment]
Ok, come link devi mettere proprio la pagina in cui ci sono i materiali, non del corso in generale, quindi nel tuo caso sarebbe `https://[gprossirwm].ariel.ctu.unimi.it/v5/frm3/ThreadList.aspx?fc=1kDFqPJxFypGQJkeRxL4BwzJUGHgKiXTTcidX%2b2YAmJOvTpCYBbCdeoUxle1UGkD&roomid=223194 ` (ovviamente senza parantesi quadre)
